infrastructure:
  kafka:
    enabled: true
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:172.16.88.115:9092}
    client-id: bank-iot-platform

    producer:
      acks: all
      enable-idempotence: true
      retries: 10
      max-in-flight-requests-per-connection: 5

    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    listener:
      auto-startup: true
      missing-topics-fatal: false


spring:

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null


  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  level:
    root: INFO

bank-iot-platform:
  application:
    environment: local

  redis:
    enabled: true
    host: localhost
    port: 6379
    database: 0
    password: ""

  oracle:
    enabled: false
    jdbc-url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: bank-iot-platform
    password: change-me
    maximum-pool-size: 10

  mongodb:
    enabled: false
    uri: mongodb://localhost:27017
    database: bank-iot-platform

  vault:
    enabled: false
    uri: http://localhost:8200