spring:
  application:
    name: session-manager-service

bank-iot-platform:

  redis:
    enabled: true

  kafka:
    enabled: true

    consumer:
      group-id: session-manager-service

  session:
    ttl: 86400