spring:
  application:
    name: session-manager-service

bank-iot-platform:

  redis:
    enabled: true

  kafka:
    enabled: true

    consumer:
      group-id: session-manager-service

  session:
    ttl: 86400

infrastructure:
  kafka:
    consumer:
      group-id: session-manager-service

      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      max-poll-records: 500
      max-poll-interval-ms: 300000

      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.isc.contract.event.session"
        spring.json.use.type.headers: true

    listener:
      ack-mode: manual_immediate
      concurrency: 3