spring:
  application:
    name: transaction-service

bank-iot-platform:

  redis:
    enabled: true

  kafka:
    enabled: true

    consumer:
      group-id: transaction-service

  oracle:
    enabled: true