server:
  port: ${SERVER_PORT:8083}

token:
  service:
    enabled: true
    issuer: ${TOKEN_ISSUER:isc-token-service}
    audience: ${TOKEN_AUDIENCE:isc-services}
    clock-skew: 30s
    access-token-lifetime: 15m
    refresh-token-lifetime: 30d

  jwt:
    algorithm: RS256
    key-id-prefix: jwt
    access-token-lifetime: 15m
    refresh-token-lifetime: 30d

    key-policy:
      key-name: ${TOKEN_JWT_KEY_NAME:bank-jwt-v2}
      algorithm: RS256
      rotation-interval: 30d
      publication-overlap: 7d
      max-published-versions: 3

      # KV v2 secret path, WITHOUT /v1/ and WITHOUT /data/
      policy-path: ${TOKEN_JWT_POLICY_PATH:key-management/bank-jwt}

      # KV mount
      policy-mount: ${TOKEN_JWT_POLICY_MOUNT:kv}

common:
  vault:
    enabled: ${COMMON_VAULT_ENABLED:true}
    uri: ${VAULT_URI:http://172.16.88.115:8200}
    token: ${VAULT_TOKEN:root}

    kv:
      enabled: true
      mount: ${VAULT_KV_MOUNT:kv}

    transit:
      enabled: true
      mount: ${VAULT_TRANSIT_MOUNT:transit}

  security:
    enabled: false

  web:
    enabled: true
    security-enabled: false
    authentication-enabled: false
