-- Apply with the Oracle schema owner before enabling delivery-service.
-- PAYLOAD is CLOB so the service can carry arbitrary JSON/text messages.
CREATE TABLE IOT_DELIVERY_MESSAGE (
    MESSAGE_ID VARCHAR2(128) NOT NULL,
    CLIENT_ID VARCHAR2(256) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    DELIVERY_STATE VARCHAR2(16) NOT NULL,
    ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    FAILURE_REASON VARCHAR2(2000),
    CONSTRAINT PK_IOT_DELIVERY_MESSAGE PRIMARY KEY (MESSAGE_ID),
    CONSTRAINT CK_IOT_DELIVERY_STATE CHECK (DELIVERY_STATE IN ('PENDING', 'DELIVERED', 'FAILED', 'ARCHIVED'))
);

CREATE INDEX IX_IOT_DELIVERY_STATE ON IOT_DELIVERY_MESSAGE (DELIVERY_STATE, UPDATED_AT);
