server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: client-identity-service
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_URL:http://localhost:9000}
        auto-registration: true
        instance:
          prefer-ip: true

client-identity:
  challenge-ttl: ${CLIENT_IDENTITY_CHALLENGE_TTL:2m}

common:
  redis:
    enabled: ${COMMON_REDIS_ENABLED:true}
    url: ${REDIS_URL:redis://172.16.88.115:6379}
    password: ${REDIS_PASSWORD:StrongRedisPassword}
    database: ${REDIS_DATABASE:0}
    timeout: ${REDIS_TIMEOUT:2s}

  security:
    enabled: false

  web:
    enabled: true
    security-enabled: false
    authentication-enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*" #health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always #when-authorized

info:
  app:
    name: client-identity-service
    description: Client identity service
    version: 1.0.0

logging:
  level:
    com.isc.clientidentity: INFO
    com.isc.common: WARN