spring:
  application:
    name: user-identity-service
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_URL:http://localhost:9000}
        auto-registration: true
        instance:
          prefer-ip: true
  datasource:
    url: ${ORACLE_JDBC_URL:jdbc:oracle:thin:@172.16.88.115:1521:XE}
    username: ${ORACLE_USERNAME:SYSTEM}
    password: ${ORACLE_PASSWORD:oracle}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        default_schema: ${DB_SCHEMA:USER_IDENTITY}
#  data:
#    redis:
#      enabled: ${COMMON_REDIS_ENABLED:true}
#      url: ${COMMON_REDIS_URL:redis://172.16.88.115:6379}
#      password: ${REDIS_PASSWORD:StrongRedisPassword}
#      database: ${REDIS_DATABASE:0}
#      timeout: ${REDIS_TIMEOUT:2s}

  flyway:
    enabled: true
    default-schema: ${DB_SCHEMA:USER_IDENTITY}
    schemas: ${DB_SCHEMA:USER_IDENTITY}
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8087}
  servlet:
    context-path: /

app:
  identity:
    otp:
      length: 6
      ttl-seconds: 180
      max-attempts: 5
      resend-cooldown-seconds: 30
      lock-seconds: 900
    authentication:
      ttl-seconds: 300
      max-step-up-attempts: 3
    redis:
      key-prefix: "user-identity:"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.isc.useridentity: INFO
