server:
  port: 8084

camel:
  component:
    kafka:
      brokers: 172.16.88.115:9092
      group-id: bank-group
      auto-offset-reset: earliest

spring:
  application:
    name: acknowledge-service

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

  data:
    redis:
      host: 172.16.88.115
      port: 6379
      password: StrongRedisPassword
      timeout: 3000

      lettuce:
        pool:
          enabled: true
          max-active: 32
          max-idle: 16
          min-idle: 4