package com.isc.useridentity.service;
import com.isc.useridentity.api.ApiDtos; import com.isc.useridentity.domain.*; import com.isc.useridentity.entity.*; import com.isc.useridentity.exception.ApiException; import com.isc.useridentity.provider.*; import com.isc.useridentity.repository.AuthenticationTransactionRepository; import lombok.RequiredArgsConstructor; import org.springframework.data.redis.core.StringRedisTemplate; import org.springframework.stereotype.Service; import java.security.SecureRandom; import java.time.*; import java.util.*; import java.util.concurrent.TimeUnit;
@Service @RequiredArgsConstructor public class AuthenticationService {
 private final AuthenticationTransactionRepository repo; private final UserIdentityService users; private final AuthenticationPolicyService policy; private final AuditService audit; private final StringRedisTemplate redis; private final OtpDeliveryProvider otpDelivery; private final BiometricProvider biometric; private final SecureRandom random=new SecureRandom();
 private String key(String s){return "user-identity:"+s;}
 public ApiDtos.AuthenticationContext start(ApiDtos.StartAuthenticationRequest r){UserIdentity u=users.require(r.userId());users.ensureActive(u);if(r.requiredAssuranceLevel().rank()<policy.minimum(r.purpose()).rank()) throw new ApiException("ASSURANCE_TOO_LOW","Requested assurance is below the policy minimum");String id="auth-"+UUID.randomUUID();Instant exp=Instant.now().plusSeconds(300);AuthenticationTransaction t=new AuthenticationTransaction();t.setAuthenticationId(id);t.setUserId(r.userId());t.setClientId(r.clientId());t.setPurpose(r.purpose());t.setRequiredAssuranceLevel(r.requiredAssuranceLevel());t.setAchievedAssuranceLevel(AssuranceLevel.IAL_0);t.setStatus(TransactionStatus.PENDING);t.setCreatedAt(Instant.now());t.setExpiresAt(exp);repo.save(t);redis.opsForValue().set(key("tx:"+id),"PENDING",300,TimeUnit.SECONDS);audit.event(id,r.userId(),r.clientId(),"AUTH_STARTED",null,r.purpose().name());return context(t);}
 public ApiDtos.AuthenticationContext stepUp(String id,ApiDtos.StepUpRequest r){AuthenticationTransaction t=requireActive(id);if(!policy.allowed(t.getPurpose(),r.method(),r.requiredAssuranceLevel())) throw new ApiException("METHOD_NOT_ALLOWED","Authentication method cannot satisfy requested assurance");t.setRequiredAssuranceLevel(r.requiredAssuranceLevel());repo.save(t);audit.event(id,t.getUserId(),t.getClientId(),"STEP_UP_REQUESTED",r.method().name(),r.requiredAssuranceLevel().name());return context(t);}
 public ApiDtos.OtpChallengeResponse issueOtp(String id){AuthenticationTransaction t=requireActive(id);Instant now=Instant.now();String cooldown=redis.opsForValue().get(key("otp:cooldown:"+id));if(cooldown!=null) throw new ApiException("OTP_COOLDOWN","OTP resend is temporarily blocked");String challenge="otp-"+UUID.randomUUID();String code=String.format("%06d",random.nextInt(1_000_000));String hash=sha256(code);Instant exp=now.plusSeconds(180);redis.opsForValue().set(key("otp:"+challenge),id+"|"+t.getUserId()+"|"+hash,180,TimeUnit.SECONDS);redis.opsForValue().set(key("otp:cooldown:"+id),"1",30,TimeUnit.SECONDS);otpDelivery.deliver(t.getUserId(),"configured-channel",code,t.getPurpose().name());audit.event(id,t.getUserId(),t.getClientId(),"OTP_ISSUED","OTP",challenge);return new ApiDtos.OtpChallengeResponse(challenge,exp,30);}
 public ApiDtos.AuthenticationContext verifyOtp(String id,ApiDtos.OtpVerifyRequest r){AuthenticationTransaction t=requireActive(id);String stored=redis.opsForValue().get(key("otp:"+r.challengeId()));if(stored==null) throw new ApiException("OTP_EXPIRED","OTP challenge expired or invalid");String[] p=stored.split("\\|",-1);if(p.length!=3||!p[0].equals(id)||!p[1].equals(t.getUserId())) throw new ApiException("OTP_BINDING_ERROR","OTP is not bound to this authentication transaction");String attemptsKey=key("otp:attempts:"+r.challengeId());Long attempts=redis.opsForValue().increment(attemptsKey);if(attempts==1)redis.expire(attemptsKey,180,TimeUnit.SECONDS);if(attempts>5){redis.delete(key("otp:"+r.challengeId()));throw new ApiException("OTP_LOCKED","OTP attempt limit exceeded");}if(!sha256(r.code()).equals(p[2])) throw new ApiException("OTP_INVALID","Invalid OTP");redis.delete(key("otp:"+r.challengeId()));return authenticate(t,AuthenticationMethod.OTP,AssuranceLevel.IAL_2);}
 public ApiDtos.AuthenticationContext verifyBiometric(String id,ApiDtos.BiometricVerifyRequest r){AuthenticationTransaction t=requireActive(id);if(!biometric.verify(t.getUserId(),t.getClientId(),r.assertion())) throw new ApiException("BIOMETRIC_INVALID","Biometric verification failed");return authenticate(t,AuthenticationMethod.BIOMETRIC,AssuranceLevel.IAL_3);}
 public ApiDtos.AuthenticationContext get(String id){return context(requireActive(id));}
 public void revoke(String id){AuthenticationTransaction t=repo.findById(id).orElseThrow(()->new ApiException("AUTH_NOT_FOUND","Authentication transaction not found"));t.setStatus(TransactionStatus.REVOKED);repo.save(t);redis.delete(key("tx:"+id));audit.event(id,t.getUserId(),t.getClientId(),"AUTH_REVOKED",null,null);}
 public ApiDtos.AuthenticationContext verifyForToken(String id,String expectedUser,String expectedClient,AssuranceLevel required){AuthenticationTransaction t=repo.findById(id).orElseThrow(()->new ApiException("AUTH_NOT_FOUND","Authentication context not found"));if(t.getStatus()!=TransactionStatus.AUTHENTICATED||t.getExpiresAt().isBefore(Instant.now()))throw new ApiException("AUTH_CONTEXT_INVALID","Authentication context is not valid");if(expectedUser!=null&&!expectedUser.equals(t.getUserId()))throw new ApiException("USER_MISMATCH","User mismatch");if(expectedClient!=null&&!expectedClient.equals(t.getClientId()))throw new ApiException("CLIENT_MISMATCH","Client mismatch");if(!t.getAchievedAssuranceLevel().satisfies(required))throw new ApiException("ASSURANCE_NOT_SATISFIED","Required assurance not satisfied");return context(t);}
 private ApiDtos.AuthenticationContext authenticate(AuthenticationTransaction t,AuthenticationMethod m,AssuranceLevel level){if(level.rank()<t.getRequiredAssuranceLevel().rank()){t.setAchievedAssuranceLevel(level);t.setAuthenticationMethod(m);repo.save(t);audit.event(t.getAuthenticationId(),t.getUserId(),t.getClientId(),"FACTOR_VERIFIED",m.name(),level.name());return context(t);}t.setAchievedAssuranceLevel(level);t.setAuthenticationMethod(m);t.setStatus(TransactionStatus.AUTHENTICATED);t.setAuthenticatedAt(Instant.now());repo.save(t);redis.delete(key("tx:"+t.getAuthenticationId()));audit.event(t.getAuthenticationId(),t.getUserId(),t.getClientId(),"AUTHENTICATED",m.name(),level.name());return context(t);}
 private AuthenticationTransaction requireActive(String id){AuthenticationTransaction t=repo.findById(id).orElseThrow(()->new ApiException("AUTH_NOT_FOUND","Authentication transaction not found"));if(t.getStatus()!=TransactionStatus.PENDING)throw new ApiException("AUTH_NOT_PENDING","Authentication transaction is not pending");if(t.getExpiresAt().isBefore(Instant.now())){t.setStatus(TransactionStatus.EXPIRED);repo.save(t);throw new ApiException("AUTH_EXPIRED","Authentication transaction expired");}return t;}
 private ApiDtos.AuthenticationContext context(AuthenticationTransaction t){return new ApiDtos.AuthenticationContext(t.getAuthenticationId(),t.getUserId(),t.getClientId(),t.getPurpose(),t.getAuthenticationMethod(),t.getAchievedAssuranceLevel(),t.getAuthenticatedAt(),t.getExpiresAt());}
 private String sha256(String s){try{var md=java.security.MessageDigest.getInstance("SHA-256");return java.util.HexFormat.of().formatHex(md.digest(s.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
